from pydantic import BaseModel

ERROR_COMMAND_NOT_FOUND = "COMMAND_NOT_FOUND"
ERROR_COMMAND_EXECUTION_FAILED = "COMMAND_EXECUTION_FAILED"
ERROR_VALIDATION_ERROR = "VALIDATION_ERROR"
ERROR_HOST_AUDIO_SERVICE_UNAVAILABLE = "HOST_AUDIO_SERVICE_UNAVAILABLE"
ERROR_INTERNAL_ERROR = "INTERNAL_ERROR"


class ErrorResponse(BaseModel):
    error: str
    message: str
    status: int
